name: Popover Testing
on: 
  push:
    branches:
      - 'master'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm dependencies
      - run: npm install
      - name: 'run testing script'
      - run: |
              npm ci
              npm run test:ci
