name: Popover Testing
on: 
  push:
    branches:
      - 'master'
jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ngx-cxl-popover
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run test:ci
